run:
	python3 manage.py runserver localhost:8001 --nothreading --noreload

shell-django:
	python3 manage.py shell

migrate:
	python3 manage.py migrate

migrations:
	python3 manage.py makemigrations

train:
	python3 train_model.py
